### ISSUE TITLE
Generate line by line images

### ISSUE THREAD

**Issue by omarabb315** [hazemIII/Quran-OCR-data#1]
How can I extract a dataset with images of each line in the Quran paired with the text?
I want to use it for OCR model training

**Comment by hazemIII** [comment]
Data.rar with lines.mat should give you the desired output. This is a verification model and it doesn't generate data, it requires input as images of the full pages. 

In the future, refrain from opening issues for your question. You can email me or post a request. An issue is only for bugs and non-working packages.

**Comment by omarabb315** [comment]
Thanks for the reply, can provide me with a matlab snippet to extract the desired output, I am not familiar with Matlab coding, 

And sorry for asking a question as an issue but I can't find you email.

**Comment by hazemIII** [comment]
https://github.com/hazemIII/Quran-OCR-data/blob/master/lines.mat
No worries. I will set up a discussion form here soon as well. 
Thanks for your interest. :)
